Deb: Sync downstream changes upstream
- Reduce Build-Depends
  https://salsa.debian.org/mariadb-team/mariadb-10.5/-/commit/150bf990c6059a2fca95ea9bc4d108c9789b179d

  Dependencies chrpath, dh-apparmor and libarchive-dev are not needed.
  Fixes buildbot sid failures that error on:
    Unmet build dependencies: chrpath dh-apparmor libarchive-dev

- Salsa-CI: Remove mysql-5.7 upgrade in Sid test as package was removed
  https://salsa.debian.org/mariadb-team/mariadb-10.5/-/commit/6f55ac620ce26046475b2a430838367732b47d54

  Also clean away extra Salsa-CI markup not needed anymore.

- Autopkgtest: Simplify autopkgtest 'smoke' to be easier to debug
  https://salsa.debian.org/mariadb-team/mariadb-10.5/-/commit/836907989ad8d355b2f88f8013a6acb8a64cf7d9

- Autopkgtest: Skip main.failed_auth_unixsocket on armhf and i386
  https://salsa.debian.org/mariadb-team/mariadb-10.5/-/commit/74601f8b31a6c59e825089c52a1ca21545062813

diff --git a/debian/tests/smoke b/debian/tests/smoke
--- a/debian/tests/smoke
+++ b/debian/tests/smoke
@@ -24,7 +24,7 @@
 echo "Running test 'smoke'"
 set -ex
 
-# Start the deamon if it was not running. For example in Docker testing
+# Start the daemon if it was not running. For example in Docker testing
 # environments there might not be any systemd et al and the service needs to
 # be started manually.
 if ! which systemctl
@@ -66,16 +66,24 @@ DROP DATABASE testdatabase;
 DROP USER 'testuser'@'localhost';
 EOT
 
-mysql <<EOT
+# List based on what is advertised at
+# https://mariadb.com/kb/en/innodb-page-compression/#configuring-the-innodb-page-compression-algorithm
+# but disabled  with '#' the options that are not available in this binary build
+mariadb <<EOT
 SET GLOBAL innodb_compression_algorithm=lz4;
+#SET GLOBAL innodb_compression_algorithm=lzo;
+#SET GLOBAL innodb_compression_algorithm=lzma;
+#SET GLOBAL innodb_compression_algorithm=bzip2;
+#SET GLOBAL innodb_compression_algorithm=snappy;
 SET GLOBAL innodb_compression_algorithm=zlib;
 SET GLOBAL innodb_compression_algorithm=none;
 EOT
 
-# Check whether RocksDB should be installed or not.
+# Check whether RocksDB should be installed or not
 plugin=mariadb-plugin-rocksdb
 if [ "$(dpkg-architecture -qDEB_HOST_ARCH_BITS)" != 32 ] &&
-   [ "$(dpkg-architecture -qDEB_HOST_ARCH_ENDIAN)" = little ]; then
+   [ "$(dpkg-architecture -qDEB_HOST_ARCH_ENDIAN)" = little ]
+  then
   dpkg-query -W $plugin
 
   LOG=/var/lib/mysql/#rocksdb/LOG
@@ -83,8 +91,18 @@ if [ "$(dpkg-architecture -qDEB_HOST_ARCH_BITS)" != 32 ] &&
   #      mariadb-server-10.5, which happens before that of the plugin.
   [ -e $LOG ] || mysql -e "INSTALL PLUGIN RocksDB SONAME 'ha_rocksdb';"
   # XXX: rocksdb_supported_compression_types variable does not report ZSTD.
+
+  # Print RocksDB supported items so test log is easier to debug
+  grep -F " supported:" $LOG
+
+  # Check that the expected compression methods are supported
   for a in LZ4 Snappy Zlib ZSTD; do
-    grep -qE "k$a(Compression)? supported: 1" $LOG
+    if ! grep -qE "k$a(Compression)? supported: 1" $LOG
+    then
+      # Fail with explicit error message
+      echo "Error: Compression method $a not supported by RocksDB!" >&2
+      exit 1
+    fi
   done
 else
   ! dpkg-query -W $plugin
