MDEV-33750: Sync smoke test from newer version of Debian Salsa-CI
For making smoke test work sync current Debian Salsa-CI version
for making needed changes

diff --git a/debian/tests/smoke b/debian/tests/smoke
--- a/debian/tests/smoke
+++ b/debian/tests/smoke
@@ -45,28 +45,29 @@ else
   systemctl restart mariadb
 fi
 
-mariadb <<EOT
+mysql <<EOT
 CREATE DATABASE testdatabase;
 CREATE USER 'testuser'@'localhost' identified by 'testpassword';
 GRANT ALL ON testdatabase.* TO 'testuser'@'localhost';
 EOT
 
-mariadb testdatabase <<EOT
+mysql testdatabase <<EOT
 CREATE TABLE foo (bar INTEGER);
 INSERT INTO foo (bar) VALUES (41);
 EOT
 
-result=$(echo 'SELECT bar+1 FROM foo;'|mariadb --batch --skip-column-names --user=testuser --password=testpassword testdatabase)
-if [ "$result" != "42" ]; then
-       echo "Unexpected result" >&2
-       exit 1
+result=$(echo 'SELECT bar+1 FROM foo;'|mysql --batch --skip-column-names --user=testuser --password=testpassword testdatabase)
+if [ "$result" != "42" ]
+then
+  echo "Unexpected result" >&2
+  exit 1
 fi
 
-mariadb --user=testuser --password=testpassword testdatabase <<EOT
+mysql --user=testuser --password=testpassword testdatabase <<EOT
 DROP TABLE foo;
 EOT
 
-mariadb <<EOT
+mysql <<EOT
 DROP DATABASE testdatabase;
 DROP USER 'testuser'@'localhost';
 EOT
@@ -114,5 +115,9 @@ then
     fi
   done
 else
-  dpkg-query -W $plugin && exit 1
+  if dpkg-query -W $plugin
+  then
+    echo "Error: Plugin $plugin was found even though it should not exist on a 32-bit and little-endian system"
+    exit 1
+  fi
 fi
