MDEV-33750: Sync maintainer scripts etc with latest downstream 10.11.5 in Debian
Fix a large amount of minor fixes to maintainer scripts and other done
downstream in the official Debian packaging.

Changes include:

https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/38198d0b9e1c7821ddd074e308b25034bdcdce5b
> Limit check of running mysqld/mariadbd to system users (Closes: #1032047)
>
> If a random user has their own copy of mysqld/mariadbd running, the
> dpkg maintainer script should not care about it.

https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/8116354d22e0b8eade6d8f0594c57300d5d5cff5
> Make error more helpful in case server restart fails (Related: #1033234)
>
> Bugs such as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033234
> and https://bugs.launchpad.net/ubuntu/+source/mariadb-10.6/+bug/2011293
> show that currently dpkg stopping on service stop/start does not have
> a very helpful error message.

https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/8675e97202171812a1afdb438a17cb29a99836fb
> Complement upstream commits with more complete mysql->mariadb conversion
>
> The upstream commit 952af4a1 missed some places where 'mysql' or
> 'MySQL' can and should be converted to use 'mariadb' or 'MariaDB'.

https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/c98361330063e7dccbf8d21aa20e48179ba5c1e4
> Fix indentation in Debian post and pre scripts
>
> There is several misindentation inside Debian post and pre
> installation scripts. False indentation with space as indent space
> should be 2 and indentation with tabs.
>
> Adopt upstream commit 7cbb45d1 in Debian by conserving customizations
> in:
> - debian/mariadb-server.postinst
> - debian/mariadb-server.postrm
> - debian/mariadb-server.preinst

https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/d0bcab443fa6d44084dc674ba29b79516c6239ba
> Ensure spaces are used everywhere instead of tabs for indentation

https://salsa.debian.org/mariadb-team/mariadb-server/-/commit/0300a9157cc69f75e01ac9c0d6e033d8be661492
> Complement previous upstream commits to fix Shellcheck issues
>
> - Unify if/then and while/do on separate lines
> - Fix indentation to be consistent
> - Use "$()" instead of backticks for subshells
> - Exit code cannot be -1, must be 0-255
> - Remove unused variables MYCHECK and MYCHECK_PARAMS
> - Rewrite messy command-line database calls to an easier to read form
>   that does exactly the same
> - Use 'command -v' test instead of 'which'
>
> With this commit, all of debian/* is Shellcheck clean.

Also
* Update mariadb.conf.d template to tell users where to create logdir
  if they are not using journald
* Remove use of work 'slave'
* Add minor workaround for Debian Bug #1022994 if TMPDIR is empty
* Make start/stop in maintainer scripts correctly check mariadbd
  ownership and only start/stop processes owned by root or 'mysql'
* Remove obsolete 'NO_UPDATE_BUILD_VERSION=1' as it did not affect the
  RocksDB build reproducibility as previously assumed
* Run 'wrap-and-sort -av'

diff --git a/debian/tests/smoke b/debian/tests/smoke
--- a/debian/tests/smoke
+++ b/debian/tests/smoke
@@ -8,9 +8,9 @@
 #
 # This test should be declared in debian/tests/control with the
 # following restrictions:
-#
-# needs-root (to be able to log into the database)
-# allow-stderr
+# - allow-stderr (set -x always outputs to stderr)
+# - needs-root (to be able to log into the database)
+# - isolation-container (to be able to start service)
 #
 # This test:
 #
@@ -27,7 +27,7 @@ set -ex
 # Start the daemon if it was not running. For example in Docker testing
 # environments there might not be any systemd et al and the service needs to
 # be started manually.
-if ! which systemctl
+if ! command -v systemctl
 then
   if ! /etc/init.d/mariadb status
   then
@@ -71,9 +71,12 @@ DROP DATABASE testdatabase;
 DROP USER 'testuser'@'localhost';
 EOT
 
-# List based on what is advertised at
-# https://mariadb.com/kb/en/innodb-page-compression/#configuring-the-innodb-page-compression-algorithm
-# but disabled  with '#' the options that are not available in this binary build
+# This will never fail but exists purely for debugging purposes in case a later
+# step would fail
+mariadb <<EOT
+SHOW GLOBAL STATUS WHERE Variable_name LIKE 'Innodb_have_%';
+EOT
+
 mariadb <<EOT
 SET GLOBAL innodb_compression_algorithm=lz4;
 SET GLOBAL innodb_compression_algorithm=lzo;
@@ -88,7 +91,7 @@ EOT
 plugin=mariadb-plugin-rocksdb
 if [ "$(dpkg-architecture -qDEB_HOST_ARCH_BITS)" != 32 ] &&
    [ "$(dpkg-architecture -qDEB_HOST_ARCH_ENDIAN)" = little ]
-  then
+then
   dpkg-query -W $plugin
 
   LOG=/var/lib/mysql/#rocksdb/LOG
@@ -101,7 +104,8 @@ if [ "$(dpkg-architecture -qDEB_HOST_ARCH_BITS)" != 32 ] &&
   grep -F " supported:" $LOG
 
   # Check that the expected compression methods are supported
-  for a in LZ4 Snappy Zlib ZSTD; do
+  for a in LZ4 Snappy Zlib ZSTD
+  do
     if ! grep -qE "k$a(Compression)? supported: 1" $LOG
     then
       # Fail with explicit error message
@@ -110,5 +114,5 @@ if [ "$(dpkg-architecture -qDEB_HOST_ARCH_BITS)" != 32 ] &&
     fi
   done
 else
-  ! dpkg-query -W $plugin
+  dpkg-query -W $plugin && exit 1
 fi
