MDEV-6284: Sync mariadb-server maintainer scripts as much as possible
There are still some differences in due to systemd and service triggers,
but these differences make sense and are likely to be synced the other
way later so that downstream Debian official packaging adopts them.

The synced changes include among others:
- https://salsa.debian.org/mariadb-team/mariadb-10.4/-/commit/9f49e4b494f3dad8c403972996f7a1ebceb4b34f
- https://salsa.debian.org/mariadb-team/mariadb-10.4/-/commit/6440c0d6e75aeda134f4f942eee4fbfd62b1ce20
- https://salsa.debian.org/mariadb-team/mariadb-10.4/-/commit/6e5ee72d647744bf84c42e02c3dfe888912e739e
- https://salsa.debian.org/mariadb-team/mariadb-10.4/-/commit/e62e67ae4b7679c43e80a20ab3ba3c51f01f0714
- https://salsa.debian.org/mariadb-team/mariadb-10.4/-/commit/df2415a53d5604755768f00aad0c640df1ad815c
- https://salsa.debian.org/mariadb-team/mariadb-10.4/-/commit/643558da74990f8648b3c86039e253dbae337c84

diff --git a/debian/mariadb-server-10.5.postrm b/debian/mariadb-server-10.5.postrm
--- a/debian/mariadb-server-10.5.postrm
+++ b/debian/mariadb-server-10.5.postrm
@@ -1,6 +1,10 @@
-#!/bin/bash -e
+#!/bin/bash
+set -e
 
 . /usr/share/debconf/confmodule
+
+# Automatically set version to ease maintenance of this file
+MAJOR_VER="${DPKG_MAINTSCRIPT_PACKAGE#mariadb-server-}"
 
 if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
 ${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }
@@ -37,17 +41,18 @@ case "$1" in
 esac
 
 #
-# - Do NOT purge logs or data if another mysql-sever* package is installed (#307473)
+# - Purge logs and data only if they are ours (#307473)
 # - Remove the mysql user only after all his owned files are purged.
+# - Cleanup the initscripts only if this was the last provider of them
 #
-if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; then
+if [ "$1" = "purge" ] && [ -f "/var/lib/mysql/debian-$MAJOR_VER.flag" ]; then
   # we remove the mysql user only after all his owned files are purged
   rm -f /var/log/mysql.{log,err}{,.0,.[1234567].gz}
   rm -rf /var/log/mysql
 
-  db_input high mariadb-server-10.5/postrm_remove_databases || true
+  db_input high "mariadb-server-$MAJOR_VER/postrm_remove_databases" || true
   db_go || true
-  db_get mariadb-server-10.5/postrm_remove_databases || true
+  db_get "mariadb-server-$MAJOR_VER/postrm_remove_databases" || true
   if [ "$RET" = "true" ]; then
     # never remove the debian.cnf when the databases are still existing
     # else we ran into big trouble on the next install!
@@ -56,13 +61,19 @@ if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; the
     # directory with file system data. See #829491 for details and
     # #608938 for potential mysql-server leftovers which erroneously
     # had been renamed.
-    find /var/lib/mysql -mindepth 1 \
-         -not -path '*/lost+found/*'     -not -name 'lost+found' \
-         -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
-         -delete
-    # "|| true" still needed as rmdir still exits with non-zero if
-    # /var/lib/mysql is a mount point
-    rmdir --ignore-fail-on-non-empty /var/lib/mysql || true
+    # Attempt removal only if the directory hasn't already been removed
+    # by dpkg to avoid failing on "No such file or directory" errors.
+    if [ -d /var/lib/mysql ]
+    then
+      find /var/lib/mysql -mindepth 1 \
+           -not -path '*/lost+found/*'     -not -name 'lost+found' \
+           -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
+           -delete
+
+      # "|| true" still needed as rmdir still exits with non-zero if
+      # /var/lib/mysql is a mount point
+      rmdir --ignore-fail-on-non-empty /var/lib/mysql || true
+    fi
     rm -rf /var/run/mysqld # this directory is created by the init script, don't leave behind
     userdel mysql || true
   fi
@@ -70,5 +81,3 @@ if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; the
 fi
 
 #DEBHELPER#
-
-exit 0
