Deb: Add support for legacy init systems again
Partially reverts commit a4cc6fb91f3855e0ed803a6e1762440cfcf8cb5c.

While all current versions of Linux have systemd, support for traditional
init.d is still needed e.g. on Linux subsystem on Windows, kFreeBSD and
special variants of Debian/Ubuntu that for other reasons don't have
systemd.

Thus, re-introduce the init file that was remove, but this time with
then name 'mariadb'.

Supporting traditional sysv init in paraller with systemd is easy, since
Debian has facilities for it.

Also simplify and update salsa-ci.yml install/upgrade testing works
for all previous MariaDB and MySQL releases without any excess quirks.

Note that in fresh installs the salsa-ci.yml needs to run command
'service mariadb status' to control the service, while on upgrades
it is enough to run 'service mysql status', since the init.d/mysql
file is left behind from previous install, along with some other
config files such as /etc/default/mysql and /etc/mysql/* stuff.

diff --git a/debian/mariadb-server-10.5.postinst b/debian/mariadb-server-10.5.postinst
--- a/debian/mariadb-server-10.5.postinst
+++ b/debian/mariadb-server-10.5.postinst
@@ -18,17 +18,42 @@ ERR_LOGGER="logger -p daemon.err -t mariadb-server-$MAJOR_VER.postinst -i"
 # the install, rather than failing silently and leaving a broken install.
 set -o pipefail
 
-invoke() {
-  systemctl $1 mysql
-}
-
 case "$1" in
   configure)
-    # This is needed because mysql_install_db removes the pid file in /var/run
+    # This is needed because mysql_install_db removes the pid file in /run
     # and because changed configuration options should take effect immediately.
     # In case the server wasn't running at all it should be ok if the stop
-    # script fails. I can't tell at this point because of the cleaned /var/run.
-    set +e; invoke stop; set -e
+    # script fails. I can't tell at this point because of the cleaned /run.
+    set +e; invoke-rc.d mariadb stop; set -e
+
+    # An existing /etc/init.d/mysql might be on the system if there was a
+    # previous MySQL or MariaDB installation, since /etc/init.d files are
+    # considered config files and stay around even after the package is removed.
+    #
+    # The install step of this package adds a new /etc/init.d/mariadb file. As
+    # we also want to ensure that there are no old (and potentially outdated)
+    # versions of /etc/init.d/mysql we simply replace it using a copy of the
+    # latest 'mariadb' file. This has also the added benefit that anything that
+    # invokes traditional sysv init with either 'mysql' or 'mariadb' will end up
+    # controlling this newly installed MariaDB, and thus we maintain better
+    # backwards compatiblity.
+    #
+    # Note that the 'Provides' line is also updated to avoid 'insserv' exiting
+    # on failure (when it is run by update-rc.d) because of duplicate service
+    # names.
+    if [ -f "/etc/init.d/mysql" ] && [ -f "/etc/init.d/mariadb" ]
+    then
+      # Copy init file and rename the service name and filename on the fly
+      sed 's/Provides:          mariadb/Provides:          mysql/g' /etc/init.d/mariadb > /etc/init.d/mysql
+      # NOTE: Number of spaces/tabs is important here!
+      # Confirm if the sed worked
+      if ! grep --quiet "Provides:          mysql" /etc/init.d/mysql
+      then
+        # If not, then delete the file to avoid failures later on
+        rm -f /etc/init.d/mysql
+        echo "Warning! Failed creating a mysql named copy of mariadb init.d file"
+      fi
+    fi
 
     mysql_statedir=/usr/share/mysql
     mysql_datadir=/var/lib/mysql
@@ -126,7 +151,7 @@ EOF
 
     # initiate databases. Output is not allowed by debconf :-(
     # This will fail if we are upgrading an existing database; in this case
-    # mysql_upgrade, called from the /etc/init.d/mysql start script, will
+    # mysql_upgrade, called from the /etc/init.d/mariadb start script, will
     # handle things.
     # Debian: beware of the bashisms...
     # Debian: can safely run on upgrades with existing databases
@@ -187,8 +212,9 @@ EOF
   triggered)
     if [ -x "$(command -v systemctl)" ]; then
       systemctl daemon-reload
+    else
+      invoke-rc.d mariadb restart
     fi
-    invoke restart
   ;;
 
   *)
@@ -199,7 +225,7 @@ esac
 
 db_stop # in case invoke failes
 
-# dh_systemd_start doesn't emit anything since we still ship /etc/init.d/mysql.
+# dh_systemd_start doesn't emit anything since we still ship /etc/init.d/mariadb.
 # Thus MariaDB server is started via init.d script, which in turn redirects to
 # systemctl. If we upgrade from MySQL mysql.service may be masked, which also
 # means init.d script is disabled. Unmask mysql service explicitly.
diff --git a/debian/mariadb-server-10.5.preinst b/debian/mariadb-server-10.5.preinst
--- a/debian/mariadb-server-10.5.preinst
+++ b/debian/mariadb-server-10.5.preinst
@@ -33,14 +33,14 @@ stop_server() {
     if ! pgrep -x --ns $$ mysqld > /dev/null; then return; fi
 
     set +e
-    systemctl stop mysql
+    invoke-rc.d mariadb stop
     errno=$?
     set -e
 
-    # 0=ok, 100=no init script (fresh install)
+    # systemctl could emit exit code 100=no init script (fresh install)
     if [ "$errno" != 0 -a "$errno" != 100 ]; then
-      echo "'systemctl stop mysql' returned $errno" 1>&2
-      echo "There is a MySQL server running, but we failed in our attempts to stop it." 1>&2
+      echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
+      echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
       echo "Stop it yourself and try again!" 1>&2
       db_stop
       exit 1
