MDEV-23931: Deb: Add support for legacy init systems again
Partially reverts commit a4cc6fb91f3855e0ed803a6e1762440cfcf8cb5c.

While all current versions of Linux have systemd, support for traditional
init.d is still needed e.g. on Linux subsystem on Windows, kFreeBSD and
special variants of Debian/Ubuntu that for other reasons don't have
systemd (e.g. Docker containers).

Thus, re-introduce the init file that was removed, but this time with
the name 'mariadb'.

Supporting traditional sysv init in parallel with systemd is easy, since
Debian has facilities for it.

This commit was backported and adapted from commit 764dd39ca76.

diff --git a/debian/mariadb-server-10.4.postrm b/debian/mariadb-server-10.4.postrm
--- a/debian/mariadb-server-10.4.postrm
+++ b/debian/mariadb-server-10.4.postrm
@@ -9,18 +9,25 @@ MYADMIN="/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf"
 
 # Try to stop the server in a sane way. If it does not success let the admin
 # do it himself. No database directories should be removed while the server
-# is running!
+# is running! Another mysqld in e.g. a different chroot is fine for us.
 stop_server() {
-  set +e
-  systemctl stop mysql
-  errno=$?
-  set -e
+    # Return immediately if there are no mysql processes running
+    # as there is no point in trying to shutdown in that case.
+    if ! pgrep -x mysqld > /dev/null; then return; fi
 
-  if [ "$?" != 0 ]; then
-    echo "Trying to stop the MySQL server resulted in exitcode $?." 1>&2
-    echo "Stop it yourself and try again!" 1>&2
-    exit 1
-  fi
+    set +e
+    invoke-rc.d mariadb stop
+    errno=$?
+    set -e
+
+    # systemctl could emit exit code 100=no init script (fresh install)
+    if [ "$errno" != 0 -a "$errno" != 100 ]; then
+      echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
+      echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
+      echo "Stop it yourself and try again!" 1>&2
+      db_stop
+      exit 1
+    fi
 }
 
 case "$1" in
@@ -63,7 +70,7 @@ if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; the
     # "|| true" still needed as rmdir still exits with non-zero if
     # /var/lib/mysql is a mount point
     rmdir --ignore-fail-on-non-empty /var/lib/mysql || true
-    rm -rf /var/run/mysqld # this directory is created by the init script, don't leave behind
+    rm -rf /run/mysqld # this directory is created by the init script, don't leave behind
     userdel mysql || true
   fi
 
