MDEV-40964: Update default datadir for debian to be /var/lib/mariadb
Match the existing datadir setting for Debian and Ubuntu, which was
changed from /var/lib/mysql to /var/lib/mariadb in 1:11.8.6-5. This
includes updating debian/ packaging to use /var/lib/mariadb for new
installs, and maintaining /var/lib/mysql for legacy installs by
providing 99-legacy-datadir.cnf. Likewise, update the cmake
INSTALL_MYSQLDATADIR_DEB variable to reflect the change. The debian flag-based version check system has also been replaced as it is no
longer needed.

diff --git a/debian/mariadb-server.postrm b/debian/mariadb-server.postrm
--- a/debian/mariadb-server.postrm
+++ b/debian/mariadb-server.postrm
@@ -12,16 +12,70 @@ fi
 
 ${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }
 
+mariadb_datadir=/var/lib/mariadb
+legacy_mariadb_datadir=/var/lib/mysql
+
+# Check if the version file mariadb_upgrade_info or mysql_upgrade_info is
+# included with the provided data directory. If it is a MariaDB version, then
+# return the major version number only (XX.XX). Return empty if this directory
+# does not belong to MariaDB.
+get_mariadb_upgrade_info_major_version() {
+  datadir="$1"
+
+  # Check both mariadb_upgrade_info (higher priority) and mysql_upgrade_info.
+  if [ -f "$datadir/mysql_upgrade_info" ]
+  then
+    read -r full_version < "$datadir/mysql_upgrade_info"
+  fi
+
+  if [ -f "$datadir/mariadb_upgrade_info" ]
+  then
+    read -r full_version < "$datadir/mariadb_upgrade_info"
+  fi
+
+  # If version is not empty and contains 'MariaDB', get the version number.
+  if [ -n "$full_version" ] && echo "$full_version" | grep -q "MariaDB"
+  then
+    # The major version number should the first two components of the version
+    # string (e.g. 11.8 from 11.8.6).
+    echo "$full_version" | awk -F'.' '{print $1"."$2}'
+  fi
+}
+
 #
 # - Purge logs and data only if they are ours (#307473)
 # - Remove the mysql user only after all his owned files are purged.
 # - Cleanup the initscripts only if this was the last provider of them
 #
-if [ "$1" = "purge" ] && [ -f "/var/lib/mysql/debian-__MARIADB_MAJOR_VER__.flag" ]
+if [ "$1" = "purge" ]
 then
-  # we remove the mysql user only after all his owned files are purged
-  rm -f /var/log/mysql.{log,err}{,.0,.[1234567].gz}
-  rm -rf /var/log/mysql
+  rm -f /etc/mysql/mariadb.conf.d/99-legacy-datadir.cnf
+
+  # Mark data directories for removal if they match the current MariaDB version.
+  remove_mariadb_datadir="false"
+  remove_legacy_mariadb_datadir="false"
+
+  mariadb_datadir_version=$(get_mariadb_upgrade_info_major_version "$mariadb_datadir")
+
+  if [ "$mariadb_datadir_version" = "__MARIADB_MAJOR_VER__" ]
+  then
+    remove_mariadb_datadir="true"
+  fi
+
+  legacy_mariadb_datadir_version=$(get_mariadb_upgrade_info_major_version "$legacy_mariadb_datadir")
+
+  if [ "$legacy_mariadb_datadir_version" = "__MARIADB_MAJOR_VER__" ]
+  then
+    remove_legacy_mariadb_datadir="true"
+  fi
+
+  # Remove logs in /var/log/mysql only if they are ours.
+  # These must be removed before mysql user is removed.
+  if [ "$remove_mariadb_datadir" = "true" ] || [ "$remove_legacy_mariadb_datadir" = "true" ]
+  then
+    rm -f /var/log/mysql.{log,err}{,.0,.[1234567].gz}
+    rm -rf /var/log/mysql
+  fi
 
   db_input high "mariadb-server/postrm_remove_databases" || true
   db_go || true
@@ -30,26 +84,47 @@ then
   then
     # never remove the debian.cnf when the databases are still existing
     # else we ran into big trouble on the next install!
-    rm -f /etc/mysql/debian.cnf
-    # Remove all contents from /var/lib/mysql except if it's a
+    if [ "$remove_mariadb_datadir" = "true" ] || [ "$remove_legacy_mariadb_datadir" = "true" ]
+    then
+      rm -f /etc/mysql/debian.cnf
+    fi
+    # Remove all contents from /var/lib/mariadb except if it's a
     # directory with file system data. See #829491 for details and
     # #608938 for potential mysql-server leftovers which erroneously
     # had been renamed.
     # Attempt removal only if the directory hasn't already been removed
     # by dpkg to avoid failing on "No such file or directory" errors.
-    if [ -d /var/lib/mysql ]
+    if [ "$remove_mariadb_datadir" = "true" ]
     then
-      find /var/lib/mysql -mindepth 1 \
+      find "$mariadb_datadir" -mindepth 1 \
+        -not -path '*/lost+found/*'     -not -name 'lost+found' \
+        -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
+        -delete
+
+      # "|| true" still needed as rmdir still exits with non-zero if
+      # /var/lib/mariadb is a mount point
+      rmdir --ignore-fail-on-non-empty "$mariadb_datadir" || true
+    fi
+    # Remove all contents from /var/lib/mysql if it's owned by us, with same
+    # checks as /var/lib/mariadb.
+    if [ "$remove_legacy_mariadb_datadir" = "true" ]
+    then
+      find "$legacy_mariadb_datadir" -mindepth 1 \
         -not -path '*/lost+found/*'     -not -name 'lost+found' \
         -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
         -delete
 
       # "|| true" still needed as rmdir still exits with non-zero if
       # /var/lib/mysql is a mount point
-      rmdir --ignore-fail-on-non-empty /var/lib/mysql || true
+      rmdir --ignore-fail-on-non-empty "$legacy_mariadb_datadir" || true
     fi
-    rm -rf /run/mysqld # this directory is created by the init script, don't leave behind
-    userdel mysql || true
+
+    # Remove /run/mysqld and mysql user if owned by us.
+    if [ "$remove_mariadb_datadir" = "true" ] || [ "$remove_legacy_mariadb_datadir" = "true" ]
+    then
+      rm -rf /run/mysqld # this directory is created by the init script, don't leave behind
+      userdel mysql || true
+    fi
   fi
 
 fi
diff --git a/debian/mariadb-server.preinst b/debian/mariadb-server.preinst
--- a/debian/mariadb-server.preinst
+++ b/debian/mariadb-server.preinst
@@ -26,7 +26,8 @@ fi
 ${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }
 
 export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin
-mariadb_datadir=/var/lib/mysql
+mariadb_datadir=/var/lib/mariadb
+legacy_mariadb_datadir=/var/lib/mysql
 mariadb_upgradedir=/var/lib/mysql-upgrade
 
 MARIADBD_USERS="root"
@@ -67,46 +68,48 @@ stop_server() {
   fi
 }
 
+# Check if the version file mariadb_upgrade_info or mysql_upgrade_info is
+# included with the provided data directory. If it is a MariaDB version, then
+# return the major version number only (XX.XX). Return empty if this directory
+# does not belong to MariaDB.
+get_mariadb_upgrade_info_major_version() {
+  datadir="$1"
+
+  # Check both mariadb_upgrade_info (higher priority) and mysql_upgrade_info.
+  if [ -f "$datadir/mysql_upgrade_info" ]
+  then
+    read -r full_version < "$datadir/mysql_upgrade_info"
+  fi
+
+  if [ -f "$datadir/mariadb_upgrade_info" ]
+  then
+    read -r full_version < "$datadir/mariadb_upgrade_info"
+  fi
+
+  # If version is not empty and contains 'MariaDB', get the major version.
+  [[ $full_version =~ MariaDB ]] && echo ${full_version%.*}
+}
+
 ################################ main() ##########################
 
-# @TODO: Rewrite this to use the new upstream /var/lib/mysql_upgrade_info file
-# instead of the legacy /var/lib/debian-XX.X.flag file
 this_version=__MARIADB_MAJOR_VER__
 max_upgradeable_version=5.7
 
-# Check if a flag file is found that indicates a previous MariaDB or MySQL
-# version was installed. If multiple flags are found, check which one was
-# the biggest version number.
-for flag in "$mariadb_datadir"/debian-*.flag
-do
+# Check for previous mariadb version in the new datadir.
+found_version=$(get_mariadb_upgrade_info_major_version "$mariadb_datadir")
 
-  # The for loop leaves $flag as the query string if there are no results,
-  # so the check below is needed to stop further processing when there are
-  # no real results.
-  if [ "$flag" = "$mariadb_datadir/debian-*.flag" ]
+# If nothing was found in the new datadir, check the legacy datadir to see if
+# it has a MariaDB instance.
+if [ -z "$found_version" ] && [ -d "$legacy_mariadb_datadir" ]
+then
+  found_version=$(get_mariadb_upgrade_info_major_version "$legacy_mariadb_datadir")
+
+  # If a mariadb version was found in the legacy datadir, continue using it.
+  if [ -n "$found_version" ]
   then
-    break
+    mariadb_datadir="$legacy_mariadb_datadir"
   fi
-
-  # The whole flag_version thing should be rewritten, so ignore minor Shellcheck
-  # nag for now
-  # shellcheck disable=SC2001
-  flag_version=$(echo "$flag" | sed 's/.*debian-\([0-9\.]\+\).flag/\1/')
-
-  # Initialize value if empty
-  if [ -z "$found_version" ]
-  then
-    found_version=$flag_version
-  fi
-
-  # Update value if now bigger then before
-  if dpkg --compare-versions "$flag_version" '>>' "$found_version"
-  then
-    found_version=$flag_version
-  fi
-
-done
-
+fi
 
 # If an upgrade is detected, proceed with it automatically without
 # requiring any user interaction.
@@ -117,16 +120,6 @@ done
 # than $max_upgradeable_version.
 if [ -n "$found_version" ]
 then
-
-  # MySQL 8.0 in Ubuntu has a bug in packaging and the file is name wrongly
-  # 'debian-5.7.flag', so in case '5.7' was encountered an extra check needs to
-  # be done to see is there is a file called undo_001, which is a sign of 8.0.
-  if [ "$found_version" == "5.7" ] && [ -f "$mariadb_datadir/undo_001" ]
-  then
-    # Seems to be a 8.0, flag has wrongly 5.7 (know bug)
-    found_version=8.0
-  fi
-
   echo "$mariadb_datadir: found previous version $found_version"
 
   if dpkg --compare-versions "$found_version" '>>' "$this_version"
@@ -142,28 +135,15 @@ then
 
 fi
 
-# If there is no debian-*.flag, and no version was detected, but a file that
-# indicated MySQL 8.0 is found (undo_001 is created by default in MySQL 8.0+
-# installs), then that file is enough of additional indication to trigger the
-# move of the data directory.
-if [ -z "$found_version" ] &&
-   [ -z "$(find $mariadb_datadir/debian-*.flag 2> /dev/null)" ] &&
-   [ -f "$mariadb_datadir/undo_001" ]
-then
-  echo "$mariadb_datadir: no server version flag found, assuming MySQL 8.0 data encountered"
-  downgrade_detected=true
-  found_version="previous" # Just use dummy name as we don't know real version
-fi
-
 # Don't abort dpkg if downgrade is detected (as was done previously).
 # Instead simply move the old datadir and create a new for this_version.
 if [ -n "$downgrade_detected" ]
 then
   db_input critical "mariadb-server/old_data_directory_saved" || true
   db_go
-  echo "The file $mariadb_datadir/debian-$found_version.flag indicates a" 1>&2
-  echo "version that cannot automatically be upgraded. Therefore the" 1>&2
-  echo "previous data directory will be renamed to $mariadb_datadir-$found_version and" 1>&2
+  echo "The $mariadb_datadir upgrade info file indicates a version that" 1>&2
+  echo "cannot automatically be upgraded. Therefore the previous data" 1>&2
+  echo "directory will be renamed to $mariadb_datadir-$found_version and" 1>&2
   echo "a new data directory will be initialized at $mariadb_datadir." 1>&2
   echo "Please manually export/import your data (e.g. with mysqldump) if needed." 1>&2
   mv -f "$mariadb_datadir" "$mariadb_datadir-$found_version"
